/**
 * AEGISOS Core Event & System Constants
 */

export const SystemEvents = Object.freeze({
  APPLICATION_STARTED: 'APPLICATION_STARTED',
  APPLICATION_SHUTDOWN: 'APPLICATION_SHUTDOWN',
  NOTE_CREATED: 'NOTE_CREATED',
  NOTE_UPDATED: 'NOTE_UPDATED',
  NOTE_DELETED: 'NOTE_DELETED',
  FILE_CHANGED: 'FILE_CHANGED',
  CHAT_MESSAGE: 'CHAT_MESSAGE',
  FLASHCARD_REVIEWED: 'FLASHCARD_REVIEWED',
  MODEL_CHANGED: 'MODEL_CHANGED',
  PROJECT_OPENED: 'PROJECT_OPENED',
  SERVICE_STARTED: 'SERVICE_STARTED',
  SERVICE_STOPPED: 'SERVICE_STOPPED',
  AGENT_REGISTERED: 'AGENT_REGISTERED',
  AGENT_STATUS_CHANGED: 'AGENT_STATUS_CHANGED',
  AGENT_STARTED: 'AGENT_STARTED',
  AGENT_COMPLETED: 'AGENT_COMPLETED',
  AGENT_FAILED: 'AGENT_FAILED',
  PLANNER_UPDATED: 'PLANNER_UPDATED',
  REASONING_GENERATED: 'REASONING_GENERATED',
  MEMORY_CREATED: 'MEMORY_CREATED',
  MEMORY_UPDATED: 'MEMORY_UPDATED',
  KNOWLEDGE_INDEXED: 'KNOWLEDGE_INDEXED',
  WORKFLOW_STARTED: 'WORKFLOW_STARTED',
  WORKFLOW_COMPLETED: 'WORKFLOW_COMPLETED',
  TOOL_EXECUTED: 'TOOL_EXECUTED',
  AUTOMATION_TRIGGERED: 'AUTOMATION_TRIGGERED',
  POLICY_VIOLATION: 'POLICY_VIOLATION',
  PROJECT_CHANGED: 'PROJECT_CHANGED',
  COMPANION_SUGGESTION: 'COMPANION_SUGGESTION',
  COMPANION_LOOP_TICK: 'COMPANION_LOOP_TICK',
  SKILL_EXECUTED: 'SKILL_EXECUTED'
});

export const ServiceNames = Object.freeze({
  DATABASE: 'Database',
  RAG: 'RAG',
  EMBEDDING: 'Embedding',
  WATCHER: 'Watcher',
  CHAT: 'Chat',
  MEMORY: 'Memory',
  PLANNER: 'Planner',
  VOICE: 'Voice',
  AUTOMATION: 'Automation',
  SENTINEL: 'Sentinel',
  AGENT_RUNTIME: 'AgentRuntime',
  TOOL_RUNTIME: 'ToolRuntime',
  WORKFLOW: 'Workflow',
  GOVERNANCE: 'Governance',
  COMPANION: 'Companion'
});

export const EventSeverity = Object.freeze({
  DEBUG: 'DEBUG',
  INFO: 'INFO',
  WARN: 'WARN',
  ERROR: 'ERROR',
  CRITICAL: 'CRITICAL'
});

export const AgentStatus = Object.freeze({
  UNREGISTERED: 'UNREGISTERED',
  REGISTERED: 'REGISTERED',
  IDLE: 'IDLE',
  RUNNING: 'RUNNING',
  PAUSED: 'PAUSED',
  DISABLED: 'DISABLED',
  ERROR: 'ERROR'
});
