/**
 * AEGISOS Core Event & System Constants
 */

export const SystemEvents = Object.freeze({
  APPLICATION_STARTED: 'APPLICATION_STARTED',
  APPLICATION_SHUTDOWN: 'APPLICATION_SHUTDOWN',
  NOTE_CREATED: 'NOTE_CREATED',
  NOTE_UPDATED: 'NOTE_UPDATED',
  NOTE_DELETED: 'NOTE_DELETED',
  FILE_CHANGED: 'FILE_CHANGED',
  CHAT_MESSAGE: 'CHAT_MESSAGE',
  FLASHCARD_REVIEWED: 'FLASHCARD_REVIEWED',
  MODEL_CHANGED: 'MODEL_CHANGED',
  PROJECT_OPENED: 'PROJECT_OPENED',
  SERVICE_STARTED: 'SERVICE_STARTED',
  SERVICE_STOPPED: 'SERVICE_STOPPED',
  AGENT_REGISTERED: 'AGENT_REGISTERED',
  AGENT_STATUS_CHANGED: 'AGENT_STATUS_CHANGED',
  SKILL_EXECUTED: 'SKILL_EXECUTED'
});

export const ServiceNames = Object.freeze({
  DATABASE: 'Database',
  RAG: 'RAG',
  EMBEDDING: 'Embedding',
  WATCHER: 'Watcher',
  CHAT: 'Chat',
  MEMORY: 'Memory',
  PLANNER: 'Planner',
  VOICE: 'Voice',
  AUTOMATION: 'Automation'
});

export const AgentStatus = Object.freeze({
  UNREGISTERED: 'UNREGISTERED',
  REGISTERED: 'REGISTERED',
  IDLE: 'IDLE',
  RUNNING: 'RUNNING',
  PAUSED: 'PAUSED',
  DISABLED: 'DISABLED',
  ERROR: 'ERROR'
});
