export const MissionStateEnum = {
  IDLE: 'Idle',
  INTENT_RECEIVED: 'IntentReceived',
  INTENT_CLASSIFIED: 'IntentClassified',
  MISSION_DRAFTED: 'MissionDrafted',
  MISSION_VALIDATED: 'MissionValidated',
  MISSION_CREATED: 'MissionCreated',
  PLANNING_STARTED: 'PlanningStarted',
  DEPENDENCIES_RESOLVED: 'DependenciesResolved',
  CAPABILITIES_ASSIGNED: 'CapabilitiesAssigned',
  EXECUTION_PLAN_READY: 'ExecutionPlanReady',
  WAITING_FOR_EXECUTION: 'WaitingForExecution',
  PLANNING: 'Planning',
  CONTEXT_LOADING: 'ContextLoading',
  AGENT_ALLOCATION: 'AgentAllocation',
  EXECUTION: 'Execution',
  REFLECTION: 'Reflection',
  MEMORY_UPDATE: 'MemoryUpdate',
  COMPLETED: 'Completed',
  CANCELLED: 'Cancelled',
  FAILED: 'Failed',
};

export const RuntimeEventTypes = {
  MISSION_CREATED: 'MissionCreated',
  MISSION_UPDATED: 'MissionUpdated',
  MISSION_COMPLETED: 'MissionCompleted',
  MISSION_CANCELLED: 'MissionCancelled',
  PLANNER_STARTED: 'PlannerStarted',
  PLANNER_FINISHED: 'PlannerFinished',
  AGENT_CREATED: 'AgentCreated',
  AGENT_THINKING: 'AgentThinking',
  AGENT_EXECUTING: 'AgentExecuting',
  EXECUTION_STARTED: 'ExecutionStarted',
  EXECUTION_COMPLETED: 'ExecutionCompleted',
  CONTEXT_UPDATED: 'ContextUpdated',
  MEMORY_RETRIEVED: 'MemoryRetrieved',
  WORKSPACE_CHANGED: 'WorkspaceChanged',
  PROVIDER_CHANGED: 'ProviderChanged',
};
